#!/bin/sh
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="SGP";try ARM_mask;catch; disp("error_SGP"); end; quit' >sgp.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="TWP";try ARM_mask;catch; disp("error_TWP"); end; quit' >twp.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="ENA";try ARM_mask;catch; disp("error_ENA"); end; quit' >ena.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="OLI";try ARM_mask;catch; disp("error_OLI"); end; quit' >oli.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="NSA";try ARM_mask;catch; disp("error_NSA"); end; quit' >nsa.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="ASI";try ARM_mask;catch; disp("error_ASI"); end; quit' >asi.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="AWR";try ARM_mask;catch; disp("error_AWR"); end; quit' >awr.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="SGP";try ARM_mask_mmcr;catch; disp("error_SGP_MMCF"); end; quit' >sgp_mmcr.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="TWP";try ARM_mask_mmcr;catch; disp("error_TWP_MMCR"); end; quit' >twp_mmcr.log&
nohup matlab -nojvm -nodesktop -nosplash -r 'siteo="NSA";try ARM_mask_mmcr;catch; disp("error_NSA_MMCR"); end; quit' >nsa_mmcr.log&
